class SSOError(Exception):
    """A problem occurred during an SSO process."""
